"""user payment_customer_id

Revision ID: b4c3aea32d63
Revises: dccb91cde75d
Create Date: 2026-08-06 01:11:52.258340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4c3aea32d63'
down_revision: Union[str, Sequence[str], None] = 'dccb91cde75d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('payment_customer_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'payment_customer_id')
    # ### end Alembic commands ###
