"""subscription data model

Revision ID: dccb91cde75d
Revises: aa400765b2f6
Create Date: 2026-08-06 00:31:10.604308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dccb91cde75d'
down_revision: Union[str, Sequence[str], None] = 'aa400765b2f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'trialing', 'past_due', 'canceled', 'expired', name='subscriptionstatus'), server_default='active', nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_provider', sa.String(length=50), nullable=True),
    sa.Column('external_ref', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscriber_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscriber_id', 'creator_id', name='uq_subscription_subscriber_creator')
    )
    op.create_index(op.f('ix_subscription_creator_id'), 'subscription', ['creator_id'], unique=False)
    op.create_index(op.f('ix_subscription_external_ref'), 'subscription', ['external_ref'], unique=False)
    op.create_index(op.f('ix_subscription_id'), 'subscription', ['id'], unique=False)
    op.create_index(op.f('ix_subscription_subscriber_id'), 'subscription', ['subscriber_id'], unique=False)
    op.drop_constraint(op.f('creator_profile_user_id_fkey'), 'creator_profile', type_='foreignkey')
    op.create_foreign_key(
        op.f('creator_profile_user_id_fkey'),
        'creator_profile',
        'user',
        ['user_id'],
        ['id'],
        ondelete='CASCADE',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('creator_profile_user_id_fkey'), 'creator_profile', type_='foreignkey')
    op.create_foreign_key(op.f('creator_profile_user_id_fkey'), 'creator_profile', 'user', ['user_id'], ['id'])
    op.drop_index(op.f('ix_subscription_subscriber_id'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_id'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_external_ref'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_creator_id'), table_name='subscription')
    op.drop_table('subscription')
    op.execute('DROP TYPE IF EXISTS subscriptionstatus')
    # ### end Alembic commands ###
